#ifndef CHI_ROBOT_CONFIG_H
#define CHI_ROBOT_CONFIG_H

	#define R  0.33
	#define L1 0.268
	#define L2 0.160

	#define MAX_GOAL_VELOCITY_X	100
	#define MIN_GOAL_VELOCITY_X -100

	#define MAX_GOAL_VELOCITY_Y	100
	#define MIN_GOAL_VELOCITY_Y -100

	#define MAX_GOAL_VELOCITY_W	100
	#define MIN_GOAL_VELOCITY_W -100

#endif